apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
  labels:
    app: app
spec:
  replicas: 2 # Number of desired pods
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: # Replace with your app image
        ports:
        - containerPort: 80
        # env:
        # - name: USERNAME
        #   valueFrom:
        #     secretKeyRef:
        #       name: secret-app
        #       key: username
        # - name: PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: secret-app
        #       key: password
        # resources:
        #   requests:
        #     cpu: 50m
        #     memory: 64MB
        #   limits: 
        #     cpu: 100m
        #     memory: 128MB
            
