apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
  labels:
    app: app
spec:
  replicas: 2 # Number of desired pods
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: ghcr.io/alinhantoiu/app:latest
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits: 
            cpu: 100m
            memory: 128Mi
        ports:
        - containerPort: 8080
        env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: secret-app
              optional: true
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-app
              optional: true
              key: password

