apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: app
spec:
  selector:
    app: simple-app # This matches the label of the pods you want to expose
  ports:
    - protocol: TCP
      port: 80 # Port that the service will expose
      targetPort: 80 # Port on the container
  type: ClusterIP # Use NodePort or LoadBalancer if external access is needed
