apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: app
spec:
  selector:
    app: app # This matches the label of the pods you want to expose
  ports:
    - protocol: TCP
      port: 8080 # Port that the service will expose
      targetPort: 8080 # Port on the container
  type: ClusterIP # Use NodePort or LoadBalancer if external access is needed
